{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "52fe6d97-bca5-4e04-975d-2de5c261cd9b",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2025-06-18T18:47:54.533450Z",
     "iopub.status.busy": "2025-06-18T18:47:54.533140Z",
     "iopub.status.idle": "2025-06-18T18:47:54.540535Z",
     "shell.execute_reply": "2025-06-18T18:47:54.539766Z",
     "shell.execute_reply.started": "2025-06-18T18:47:54.533428Z"
    }
   },
   "source": [
    "# Exploratory Data Analysis for Variable Star Mapping on Simulated/Real Data\n",
    "\n",
    "## Overview\n",
    "This project uses simulated Rubin Observatory data to identify pulsating variable stars, specifically RR Lyrae, Cepheids, and Miras/LPVs and extract their light curve characteristics. These stars act as standard candles for measuring cosmic distances. Ultimately, our goal is to construct 3D spatial maps of the Milky Way and nearby satellite galaxies such as Fornax.\n",
    "\n",
    "We leverage tools like PSF photometry, variability statistics, and time-series analysis to:\n",
    "1) Detect candidate variable stars\n",
    "2) Measure brightness and period\n",
    "3) Prepare the data for classification and mapping\n",
    "\n",
    "**EDA Goals**\n",
    "\n",
    "Exploratory Data Analysis helps us:\n",
    "1) Understand data quality and structure\n",
    "2) Explore variability across multiple photometric bands (g, r, i)\n",
    "3) Filter out false positives (e.g., noise, outliers, low-signal detections)\n",
    "4) Develop robust inputs for period analysis and machine learning classification\n",
    "\n",
    "**Data Tables**\n",
    "\n",
    "We analyze four LSST-style data tables:\n",
    "1) DIAObject: Time-aggregated object-level variability metrics\n",
    "2) DIASource: Individual observations used to create light curves\n",
    "3) Object: Static metadata (e.g., coordinates, average magnitudes)\n",
    "4) ForcedSource: Flux measurements at known positions, used for color/variability tracking\n",
    "\n",
    "## Step 1: Data Cleaning - Validation\n",
    "\n",
    "**Goals**\n",
    "\n",
    "1) Ensure data integrity\n",
    "2) Remove missing or flagged data that may distort results\n",
    "\n",
    "**Tasks**\n",
    "\n",
    "1) Drop rows with NaN, NA, or zero-valued fluxes\n",
    "2) Identify and quantify flux flags (e.g., saturation, deblending issues)\n",
    "3) Pie chart: Ratio of clean vs flagged detections\n",
    "\n",
    "**Band Comparison**\n",
    "\n",
    "Pulsating stars behave differently across photometric bands:\n",
    "1) RR Lyrae: Peak in blue/green band, short period, low metallacity, strong variation in blue bands, [g]\n",
    "2) Cepheids: peak in visible red bands, intermediate period, good balance of amplitude/stability, [r]\n",
    "3) Miras: Peak in infrared bands, long period, cool red giants, larger amplitudes in redder bands, [i]\n",
    "\n",
    "**Variability and Color Analysis Plots**\n",
    "\n",
    "1) **gPSFluxSigma vs rPSFluxSigma** - Compare blue vs red variability, helps separate RR Lyrae (high in g) from Cepheids (moderate in r)\n",
    "2) **gPSFluxSigma vs iPSFluxSigma** - Compare blue vs infrared variability, useful to isolate Miras (stronger variation in i) from RR Lyrae\n",
    "3) **rPSFluxSigma vs iPSFluxSigma** - Compare red vs redder variability, differentiates Cepheids (stronger in r) from Miras (stronger in i)\n",
    "4) **g - r vs gPSFluxSigma** - Shows how blue-red color correlates with g-band variability, RR Lyrae are usually bluer, with higher variability\n",
    "5) **r - i vs iPSFluxSigma** - Shows how red–infrared color tracks with i-band variability, great for flagging Miras, which are redder and vary more in i\n",
    "6) **g - i vs PSFluxSigma** (choose most informative band or all three) - Long baseline color, useful for separating cool vs hot variables, can highlight outliers or transition stars\n",
    "7) **Histograms of PSFluxSigma in Each Band** - Helps visualize overall variability strength distribution by band (gPSFluxSigma, rPSFluxSigma, iPSFluxSigma)\n",
    "\n",
    "**Outlier Validation**\n",
    "\n",
    "High variability metrics don’t always mean true variability. We:\n",
    "1) Select stars with high Chi², MAD, Stetson J\n",
    "2) Validate light curves for anomalies or bad data\n",
    "\n",
    "## Step 2: DIAObject EDA - Variability Metrics\n",
    "\n",
    "**Key Visualizations**\n",
    "1) Chi² vs Std Dev (per band): Identifies high-variability candidates\n",
    "2) Stetson J vs Skew (per band): Looks for asymmetric pulses (e.g., RR Lyrae rise/fall pattern)\n",
    "3) MAD vs Std Dev Histogram(per band): Compares outlier-robust and sensitive metrics\n",
    "4) Flux Range Histogram (Max - Min)(per band): Finds large-amplitude stars\n",
    "5) Chi² vs N Data Points(per band): Validates metric reliability\n",
    "6) Skew vs Std Dev (per band): Differentiates noise from true variability\n",
    "7) Stetson J vs Flux Range(per band): Flags high-priority candidates\n",
    "8) Comparison plots for 1-7\n",
    "\n",
    "**Core Columns**\n",
    "\n",
    "gPSFluxChi2, gPSFluxSigma, gPSFluxStetsonJ, gPSFluxMax, gPSFluxMin, gPSFluxMAD, gPSFluxSkew, gPSFluxLinearSlope, gPSFluxNdata\n",
    "\n",
    "**Summary Table**\n",
    "| Metric          | Description                               |\n",
    "| --------------- | ----------------------------------------- |\n",
    "| Chi², Stetson J | Variability consistency                   |\n",
    "| Sigma, MAD      | Spread and robustness                     |\n",
    "| Skew            | Asymmetry of variability                  |\n",
    "| Max/Min/Range   | Amplitude indicators                      |\n",
    "| Linear Slope    | Temporal trends (e.g., sawtooth patterns) |\n",
    "| Ndata           | Confidence indicator for above statistics |\n",
    "\n",
    "\n",
    "# Step 3: DiaSource EDA - (Light Curves)\n",
    "\n",
    "We plot raw and smoothed light curves to:\n",
    "1) Visualize brightness changes over time\n",
    "2) Prepare for period estimation using models like Lomb-Scargle\n",
    "\n",
    "**Steps**\n",
    "1) Plot midPointTai vs psFlux with psFluxErr as error bars\n",
    "2) Compute and plot rolling mean to visualize periodic patterns\n",
    "\n",
    "**Why This Matters**\n",
    "1) Variable stars \"pulse\" over time—tracking these patterns helps us:\n",
    "2) Detect variability\n",
    "3) Estimate period and amplitude\n",
    "4) Classify stars using astronomy, ML, data science, and statistics\n",
    "\n",
    "**Object Table**\n",
    "\n",
    "These are some simple metadata checks to help ensure data consistency and support downstream classification \n",
    "1) RA vs Dec scatter plot to verify spatial coverage\n",
    "2) Histograms for color indices (g - r, r - i)\n",
    "\n",
    "# Step 4: ForcedSource – Color Checks for Distance Estimation\n",
    "\n",
    "We use it to:\n",
    "1) Estimate stellar color (e.g., g - i, r - i)\n",
    "2) Support Period-Luminosity-Color (PLC) relation modeling\n",
    "3) Calculate absolute magnitudes and distances\n",
    "4) Contribute to the 3D galactic map\n",
    "\n",
    "**Summary**\n",
    "\n",
    "This EDA lays the foundation for identifying periodic variables and preparing inputs for:\n",
    "1) Distance estimation\n",
    "2) Stellar classification\n",
    "3) Galactic structure modeling\n",
    "\n",
    "By visualizing variability patterns and cleaning the data, we increase the reliability of our subsequent time-series and ML workflows."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "LSST",
   "language": "python",
   "name": "lsst"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
